#!/usr/bin/env node
/** Finite local code evolution. No cloud access, arbitrary proposals, or source-repo writes. */
import {readFileSync,writeFileSync,mkdirSync,realpathSync,lstatSync,existsSync,renameSync,unlinkSync,openSync,closeSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {dirname,join,resolve,basename} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {ALIASES,contractCases} from './routing-contract.mjs';
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
export const TARGET='tools/dashboard/public/node-resolver.mjs';
const digest=s=>createHash('sha256').update(s).digest('hex');
export function proposeResolver() {
  return `/** Generated by the bounded Red Team routing optimizer. */\nexport const aliases = Object.freeze(${JSON.stringify(ALIASES,null,2)});\nexport function resolveNode(nodes, value) {\n  if (typeof value !== 'string' || !value.trim()) return null;\n  const raw=value.trim(), key=raw.toLowerCase(), normalized=key.replace(/^red team /,'').replaceAll(' ','-');\n  return nodes.find(n=>n.id===raw || n.agent===raw || n.domain===raw || n.id===normalized || n.agent?.toLowerCase()===key) || nodes.find(n=>n.id===aliases[key]) || null;\n}\n`;
}
export function scoreResolver(resolver,nodes,cases) {
  return cases.reduce((score,c)=>score+Number((resolver(nodes,c.input)?.id||null)===c.expected),0);
}
export function decide({goldenTotal,baselineGolden,candidateGolden,baselineChallenge,candidateChallenge,nullChallenge}) {
  return baselineGolden===goldenTotal && candidateGolden===goldenTotal && candidateChallenge>baselineChallenge && candidateChallenge>nullChallenge;
}
export function verifyBoundary(root,branch,target=TARGET) {
  if(realpathSync(root)!==ROOT || !branch.startsWith('codex/') || target!==TARGET) throw Error('Evolution requires this target checkout, a codex branch, and the fixed routing file');
  for(const part of ['tools','tools/dashboard','tools/dashboard/public',TARGET]) if(lstatSync(join(ROOT,part)).isSymbolicLink()) throw Error('Evolution cannot follow symlinks');
}
export async function evolve({sessionDir,maxRounds,enabled}={}) {
  const config=JSON.parse(readFileSync(join(ROOT,'tools/evolution/config.json'),'utf8'));
  if(config.mutationTarget!==TARGET || config.azureMutation!==false || config.upstreamWrites!==false) throw Error('Invalid evolution boundary configuration');
  maxRounds ??= config.maxRounds; enabled ??= config.enabled;
  if(!enabled || ['off','0','false'].includes(process.env.REDTEAM_CODE_EVOLUTION)) return {enabled:false};
  if(!Number.isInteger(maxRounds)||maxRounds<1||maxRounds>2) throw Error('Evolution is bounded to one or two rounds');
  const branch=execFileSync('git',['branch','--show-current'],{cwd:ROOT,encoding:'utf8'}).trim();
  verifyBoundary(ROOT,branch);
  const session=realpathSync(sessionDir), engagements=realpathSync(join(ROOT,'engagements'));
  if(dirname(session)!==engagements) throw Error('Evolution audit must be in a target engagement');
  const runs=join(session,'runs');
  if(existsSync(runs)&&lstatSync(runs).isSymbolicLink())throw Error('Run directory cannot be a symlink');
  mkdirSync(runs,{recursive:true});
  if(existsSync(join(runs,'live.lock')))throw Error('Do not evolve code during an assessment');
  const lock=join(ROOT,'engagements','.code-evolution.lock'),fd=openSync(lock,'wx',0o600);
  let emit;
  try {
    const log=join(runs,'live-events.jsonl');
    if(existsSync(log)&&(!lstatSync(log).isFile()||lstatSync(log).isSymbolicLink()))throw Error('Expected a regular event log');
    const runId=randomUUID(),dir=join(runs,`evolution-${runId}`);mkdirSync(dir);
    let sequence=0;
    emit=e=>writeFileSync(log,JSON.stringify({...e,schema_version:1,id:`${runId}:${++sequence}`,ts:new Date().toISOString(),session_id:basename(session),run_id:runId,mode:'live',run_kind:'code-evolution'})+'\n',{flag:'a',mode:0o600});
    const graph=JSON.parse(readFileSync(join(ROOT,'graph/redteam.graph.json'))),nodes=[...graph.nodes,...graph.roster.map(n=>({...n,id:n.domain}))];
    const cases=contractCases(nodes),decisions=[];
    emit({type:'run.started'});
    for(let round=1;round<=maxRounds;round++) {
      const before=readFileSync(join(ROOT,TARGET),'utf8'),candidate=proposeResolver(),candidateFile=join(dir,`candidate-${round}.mjs`);
      writeFileSync(candidateFile,candidate,{mode:0o600});
      emit({type:'evolution.proposed',node_id:'evolution_propose',metrics:{revision:round},evidence_refs:[`runs/evolution-${runId}/candidate-${round}.mjs`]});
      emit({type:'message.sent',from_agent:'evolution_propose',to_agent:'evolution_evaluate',transfer:{kind:'code-candidate',bytes:Buffer.byteLength(candidate),outcome:'sent'}});
      const baseline=await import(pathToFileURL(join(ROOT,TARGET)).href+`?baseline=${runId}-${round}`);
      const proposal=await import(pathToFileURL(candidateFile).href);
      const baselineGolden=scoreResolver(baseline.resolveNode,nodes,cases.golden),candidateGolden=scoreResolver(proposal.resolveNode,nodes,cases.golden);
      const baselineChallenge=scoreResolver(baseline.resolveNode,nodes,cases.challenge),candidateChallenge=scoreResolver(proposal.resolveNode,nodes,cases.challenge);
      const nullChallenge=scoreResolver(()=>null,nodes,cases.challenge);
      const accepted=decide({goldenTotal:cases.golden.length,baselineGolden,candidateGolden,baselineChallenge,candidateChallenge,nullChallenge});
      const decision={runId,round,branch,target:TARGET,objective:'UI agent attribution on a fixed contract; not Azure security quality',baselineHash:digest(before),candidateHash:digest(candidate),golden:{total:cases.golden.length,baseline:baselineGolden,candidate:candidateGolden},challenge:{total:cases.challenge.length,baseline:baselineChallenge,candidate:candidateChallenge,nullControl:nullChallenge},accepted:false,gateAccepted:accepted,reason:accepted?'Golden preserved and challenge improved':'No strict improvement or a regression',modelTraining:false,upstreamWrites:0,azureReads:0};
      emit({type:'evolution.evaluated',node_id:'evolution_evaluate',metrics:{revision:round,baseline:baselineChallenge,observed:candidateChallenge,delta:candidateChallenge-baselineChallenge,passed:candidateGolden,checks:cases.golden.length,challenge_total:cases.challenge.length},evidence_refs:[`runs/evolution-${runId}/decision-${round}.json`]});
      if(accepted) {
        verifyBoundary(ROOT,execFileSync('git',['branch','--show-current'],{cwd:ROOT,encoding:'utf8'}).trim());
        if(digest(readFileSync(join(ROOT,TARGET)))!==decision.baselineHash)throw Error('Target changed during evaluation');
        // Candidate bytes came exclusively from the fixed generator; no external code is accepted.
        const temp=join(ROOT,TARGET+'.candidate');const out=openSync(temp,'wx',0o600);try{writeFileSync(out,candidate);}finally{closeSync(out);}renameSync(temp,join(ROOT,TARGET));
      }
      decision.accepted=accepted;
      writeFileSync(join(dir,`decision-${round}.json`),JSON.stringify(decision,null,2)+'\n',{mode:0o600});
      emit({type:accepted?'evolution.accepted':'evolution.rejected',node_id:'evolution_apply',metrics:{revision:round,delta:candidateChallenge-baselineChallenge},evidence_refs:[`runs/evolution-${runId}/decision-${round}.json`]});
      decisions.push(decision);
      if(!accepted)break;
    }
    emit({type:'run.completed',metrics:{count:decisions.length,passed:decisions.filter(x=>x.accepted).length,azure_reads:0}});
    return {runId,decisions};
  }catch(error) { emit?.({type:'run.failed'}); throw error; }finally {closeSync(fd);unlinkSync(lock);}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){try{if(process.argv.length!==3)throw Error('Usage: node tools/evolution/run.mjs engagements/<session>');console.log(JSON.stringify(await evolve({sessionDir:process.argv[2]})));}catch(error){console.error(error.message);process.exitCode=1;}}
