<#
.SYNOPSIS
    Invoke-ScopedClusterScan — run a Kubernetes / container scanner against ONLY the
    Azure-derived in-scope clusters and registries for the Azure Container & Kubernetes Agent.

.DESCRIPTION
    The cluster-active lane may only ever touch an AKS cluster or pull/scan an image from a
    registry that maps back to an in-scope Azure resource. This wrapper is the single sanctioned
    way to launch a container/cluster scanner: it derives the scope exclusively from the
    engagement allowlist

        engagements/<session>/scope/cluster-targets.json

    (generated by tools/cluster/build-cluster-targets.mjs) and re-checks the cluster-testing
    authorization gate locally (mode + cluster_testing.enabled + authorization) before doing
    anything. For image scanners (trivy/grype) it verifies that every supplied image reference
    belongs to an allowlisted *.azurecr.io registry; for cluster benchmarks (kube-bench/kubesec)
    it requires a non-empty cluster allowlist and relies on the operator having selected an
    in-scope kube context.

    Defense in depth: even if this wrapper were bypassed, the redteam-guardrails cluster hook
    (cluster-core.mjs) independently denies any kube-bench/kubesec/trivy/grype invocation that is
    not authorized, and blocks trivy/grype against an off-allowlist registry. This wrapper just
    makes the safe path easy.

    NOTHING here is on by default and the scanner itself must be installed separately. This
    wrapper NEVER mutates a workload and NEVER execs into a container.

.PARAMETER Tool
    Which scanner to run: kube-bench | kubesec | trivy | grype.

.PARAMETER Image
    For trivy/grype: the fully-qualified image reference(s) to scan. Each must be hosted on an
    allowlisted *.azurecr.io registry.

.PARAMETER Manifest
    For kubesec: path(s) to the Kubernetes manifest file(s) to scan (offline, read-only).

.PARAMETER Cwd
    Repository root (where engagement.yaml and engagements/ live). Defaults to current dir.

.PARAMETER Session
    Session directory name or path under engagements/. Defaults to the active session
    recorded in engagements/.current-session.

.PARAMETER ExtraArgs
    Additional arguments passed through to the scanner.

.PARAMETER DryRun
    Print the exact command(s) that would run, but do not execute them.

.EXAMPLE
    pwsh tools/cluster/Invoke-ScopedClusterScan.ps1 -Tool kube-bench

.EXAMPLE
    pwsh tools/cluster/Invoke-ScopedClusterScan.ps1 -Tool trivy -Image 'contoso.azurecr.io/app:1.2.3' -DryRun
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('kube-bench', 'kubesec', 'trivy', 'grype')]
    [string]$Tool,

    [string[]]$Image = @(),

    [string[]]$Manifest = @(),

    [string]$Cwd = '.',

    [string]$Session,

    [string[]]$ExtraArgs = @(),

    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Fail([string]$msg) {
    Write-Error "Invoke-ScopedClusterScan refused to run: $msg"
    exit 2
}

$repoRoot = (Resolve-Path -LiteralPath $Cwd).Path

# --- Resolve the active session + allowlist ---------------------------------------------
if (-not $Session) {
    $marker = Join-Path $repoRoot 'engagements/.current-session'
    if (-not (Test-Path -LiteralPath $marker)) {
        Fail "no active session (engagements/.current-session is missing). Run New-Session.ps1 first."
    }
    $Session = (Get-Content -LiteralPath $marker -Raw).Trim()
}
if ($Session -match '[\\/]') {
    $sessionDir = (Resolve-Path -LiteralPath (Join-Path $repoRoot $Session)).Path
} else {
    $sessionDir = Join-Path $repoRoot (Join-Path 'engagements' $Session)
}
$allowlistPath = Join-Path $sessionDir 'scope/cluster-targets.json'
if (-not (Test-Path -LiteralPath $allowlistPath)) {
    Fail "no allowlist at $allowlistPath. Generate it: node tools/cluster/build-cluster-targets.mjs --db <db> --session $sessionDir"
}

# --- Re-check the authorization gate locally (the cluster hook also enforces this) ------
$engagementYaml = Join-Path $repoRoot 'engagement.yaml'
if (-not (Test-Path -LiteralPath $engagementYaml)) {
    Fail "engagement.yaml not found at repo root; cluster-active testing requires an authorized engagement."
}
$yamlText = Get-Content -LiteralPath $engagementYaml -Raw

$mode = $null
if ($yamlText -match '(?m)^\s*mode:\s*[''"]?([\w-]+)') { $mode = $Matches[1] }
if ($mode -ne 'cluster-active-testing') {
    Fail "engagement mode is '$mode'; cluster-active scanning requires mode: cluster-active-testing."
}

# Pull the cluster_testing block (best-effort, no YAML dependency).
$ctBlock = ''
$lines = $yamlText -split "`r?`n"
$capture = $false
foreach ($line in $lines) {
    if ($line -match '^cluster_testing\s*:') { $capture = $true; continue }
    if ($capture) {
        if ($line -match '^\S' -and $line.Trim() -ne '') { break }
        $ctBlock += "$line`n"
    }
}
if ($ctBlock -notmatch '(?m)^\s*enabled:\s*[''"]?(true|yes|on|1)\b') {
    Fail "cluster_testing.enabled is not true in engagement.yaml."
}
if ($ctBlock -notmatch '(?m)^\s*attested_by:\s*[''"]?\S') {
    Fail "cluster_testing.authorization.attested_by is not set in engagement.yaml."
}
if ($ctBlock -notmatch '(?m)^\s*attestation_id:\s*[''"]?\S') {
    Fail "cluster_testing.authorization.attestation_id is not set in engagement.yaml."
}

# --- Load the allowlist JSON -------------------------------------------------------------
$doc = Get-Content -LiteralPath $allowlistPath -Raw | ConvertFrom-Json
$clusters = @()
$registries = @()
if ($doc.allowlist) {
    if ($doc.allowlist.clusters) { $clusters += $doc.allowlist.clusters }
    if ($doc.allowlist.registries) { $registries += $doc.allowlist.registries }
}
$clusters = $clusters | ForEach-Object { "$_".ToLower() } | Sort-Object -Unique
$registries = $registries | ForEach-Object { "$_".ToLower() } | Sort-Object -Unique
if (($clusters.Count + $registries.Count) -eq 0) {
    Fail "the allowlist is empty — there are no in-scope clusters or registries to scan."
}

function Test-RegistryAllowed([string]$imageRef) {
    # Extract the registry FQDN (text before the first '/').
    $reg = ($imageRef -split '/')[0].ToLower()
    foreach ($r in $registries) {
        if ($reg -eq $r) { return $true }
        if ($r -notmatch '\.' -and $reg -eq "$r.azurecr.io") { return $true }
    }
    return $false
}

# --- Build the scanner invocation(s), scoped to the allowlist ----------------------------
$invocations = @()
switch ($Tool) {
    'kube-bench' {
        if ($clusters.Count -eq 0) { Fail "no in-scope clusters on the allowlist for kube-bench." }
        Write-Host "Scope: $($clusters.Count) in-scope cluster(s); kube-bench runs against the current kube context." -ForegroundColor Cyan
        Write-Host "Ensure the active kube context targets an in-scope cluster: $($clusters -join ', ')" -ForegroundColor DarkGray
        $invocations += , (@('kube-bench', 'run') + $ExtraArgs)
    }
    'kubesec' {
        if ($Manifest.Count -eq 0) { Fail "kubesec requires -Manifest <path> (offline manifest scan)." }
        foreach ($m in $Manifest) {
            if (-not (Test-Path -LiteralPath $m)) { Fail "manifest not found: $m" }
            $invocations += , (@('kubesec', 'scan', $m) + $ExtraArgs)
        }
    }
    'trivy' {
        if ($Image.Count -eq 0) { Fail "trivy requires -Image <ref> (image hosted on an allowlisted registry)." }
        foreach ($img in $Image) {
            if (-not (Test-RegistryAllowed $img)) {
                Fail "image '$img' is not on an allowlisted registry. In-scope registries: $($registries -join ', ')"
            }
            $invocations += , (@('trivy', 'image', '--scanners', 'vuln', $img) + $ExtraArgs)
        }
    }
    'grype' {
        if ($Image.Count -eq 0) { Fail "grype requires -Image <ref> (image hosted on an allowlisted registry)." }
        foreach ($img in $Image) {
            if (-not (Test-RegistryAllowed $img)) {
                Fail "image '$img' is not on an allowlisted registry. In-scope registries: $($registries -join ', ')"
            }
            $invocations += , (@('grype', $img) + $ExtraArgs)
        }
    }
}

$exe = $invocations[0][0]
if (-not (Get-Command $exe -ErrorAction SilentlyContinue)) {
    Write-Warning "'$exe' is not installed / not on PATH. Showing the scoped command(s) instead:"
    $DryRun = $true
}

foreach ($inv in $invocations) {
    $display = ($inv | ForEach-Object { if ($_ -match '\s') { '"' + $_ + '"' } else { $_ } }) -join ' '
    if ($DryRun) {
        Write-Host "DRYRUN: $display"
        continue
    }
    Write-Host "RUN: $display" -ForegroundColor Green
    & $inv[0] @($inv[1..($inv.Count - 1)])
}
